### ISSUE TITLE
DFT with open-source tools For Sequential-Circuits

### ISSUE THREAD

**Issue by mdzakirhussain** [hsluoyz/Atalanta#1]
Hello, 

I am working as a Lecturer in engineering college here in India. My Institution's name is Muffakham Jah College of Engineering and Technology, Hyderabad, India. I did my Masters in VLSI system design. 

Could you please guide me, 

1. Are there any open-source tools for DFT Sequential-Circuits, as it is stated Atalanta is for combinational circuit testing?
2. Can I give my own test vectors to the Atalanta Tool? 

Hopefully, you will help me in this regard.

**Comment by hsluoyz** [comment]
Please request here: https://www.mics.ece.vt.edu/ICDesign/CADTools/request.html

**Comment by sijaykumar** [comment]
[mdzakirhussain](https://github.com/mdzakirhussain)
Hi Sir, 
 You can use Yosys open source tools for synthesis, and sky130 these are open source tools
